disabled_rules:
- line_length
- trailing_whitespace
- function_body_length

excluded:
  - Sources/Application/AppDelegate.swift
  - Sources/Application/SceneDelegate.swift

identifier_name:
    excluded:
        - id
